name: k
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_toggle_switch: ^0.8.0
  cloud_firestore: ^4.12.1
  country_picker: ^2.0.21
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_any_logo: ^1.1.1
  flutter_switch: ^0.3.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.5
  lite_rolling_switch: ^1.0.1
  lottie: ^2.7.0
  page_view_indicators: ^2.0.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  switcher_button: ^0.0.4
  the_apple_sign_in: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  persistent_bottom_nav_bar: ^5.0.2
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo-black.png"

flutter:
  uses-material-design: true
  assets:
    - assets/onboard/
    - assets/login/
    - assets/Otp/
    - assets/aadhar/
    - assets/logo/
    - assets/location/
