// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBTjmaMl9ZMWzWmUgTd84kkV0lGw62TJ0',
    appId: '1:585591171392:web:5d613aee865ac165cc72a5',
    messagingSenderId: '585591171392',
    projectId: 'hunger02',
    authDomain: 'hunger02.firebaseapp.com',
    databaseURL: 'https://hunger02-default-rtdb.firebaseio.com',
    storageBucket: 'hunger02.appspot.com',
    measurementId: 'G-TPBWNDDDP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2GGyA7ywsvQMri55x6TJqWz14wAXukBc',
    appId: '1:585591171392:android:21db613e47861358cc72a5',
    messagingSenderId: '585591171392',
    projectId: 'hunger02',
    databaseURL: 'https://hunger02-default-rtdb.firebaseio.com',
    storageBucket: 'hunger02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjub5sQrY45x2tZuHyn-Mou-gyagVlacM',
    appId: '1:585591171392:ios:e8b5248fe4dc04c6cc72a5',
    messagingSenderId: '585591171392',
    projectId: 'hunger02',
    databaseURL: 'https://hunger02-default-rtdb.firebaseio.com',
    storageBucket: 'hunger02.appspot.com',
    androidClientId: '585591171392-jg5lg13h895uolb2446k5v0k1oqf4r0v.apps.googleusercontent.com',
    iosClientId: '585591171392-qa4plqpk5hig222furiajd4njdhk6jj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjub5sQrY45x2tZuHyn-Mou-gyagVlacM',
    appId: '1:585591171392:ios:b6050f1200b90c97cc72a5',
    messagingSenderId: '585591171392',
    projectId: 'hunger02',
    databaseURL: 'https://hunger02-default-rtdb.firebaseio.com',
    storageBucket: 'hunger02.appspot.com',
    androidClientId: '585591171392-jg5lg13h895uolb2446k5v0k1oqf4r0v.apps.googleusercontent.com',
    iosClientId: '585591171392-8djcnh0cd32obus0b1so3jk7u4iflthp.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedzo.RunnerTests',
  );
}
